/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    HlsLive: typeof import('./src/components/charts/HlsLive.vue')['default']
    Me: typeof import('./src/components/me.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/upload.vue')['default']
  }
}
