/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Card: typeof import('./src/components/card/index.vue')['default']
    Color: typeof import('./src/components/Color/index.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/index.vue')['default']
    copy: typeof import('./src/components/ColorPicker/index copy.vue')['default']
    Draw: typeof import('./src/components/Panel/draw.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    HlsLive: typeof import('./src/components/Charts/HlsLive.vue')['default']
    'Index copy': typeof import('./src/components/ColorPicker/index copy.vue')['default']
    Me: typeof import('./src/components/me.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    Panel: typeof import('./src/components/Panel/index.vue')['default']
    Radar: typeof import('./src/components/Table/radar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/components/upload/index.vue')['default']
  }
}
